import type { RequestHandler } from './$types';

export const GET: RequestHandler = async () => {
	return new Response(
		`
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset
              xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
                    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
        <!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->
        
        
        <url>
          <loc>https://testlifecycle.pages.dev/</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>1.00</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/equipment-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/test-scheduling</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/test-lab-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/issue-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/test-planning</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/test-catalog-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/reporting</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/customization</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/solutions/integrations</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/customer-service/adoption-service</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/customer-service/technical-service</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/customer-service/support</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/about-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/faq</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/why-choose-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/blog</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/resource-center</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/news-and-events</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/titan-benefits</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/vehicle-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/powertrain-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/battery-and-hv-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/thermal-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/reliability-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/passive-safety-crash</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/chassis-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/functional-test-area/homologation-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/request-demo</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.80</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/contact-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/test-incident-and-concerns-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/Test-Report-Generation-Challenges-In-Automotive-Industry</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/TITAN-An-Engineers-Ally</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/I-love-making-reports.-Said-NO-ENGINEER.-EVER.</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/a-complete-guide-crash-testing-for-automobile</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/DVP-Essentials-How-TITAN-Guarantees-Comprehensive-Test-Coverage-with-Enhanced-Product-Quality</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/Standardization-Engineering-Testing-Should-Be-Standardized-too!</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/why-do-you-need-test-lifecycle-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/Maximizing-Efficiency-in-test-Management-The-Case-for-Choosing-Titan-Over-Custom-Solutions%C2%A0</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/post/Need-For-Prototype-Vehicle-Management-System</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/news-and-events/titan-news-and-event-1</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/news-and-events/titan-news-and-event</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.64</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/equipment-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/test-scheduling</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/test-lab-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/issue-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/test-planning</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/test-catalog-management</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/reporting</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/customization</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/solutions/integrations</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/customer-service/adoption-service</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/customer-service/technical-service</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/customer-service/support</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/about-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/faq</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/why-choose-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/blog</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/resource-center</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/news-and-events</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/titan-benefits</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/vehicle-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/powertrain-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/battery-and-hv-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/thermal-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/reliability-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/passive-safety-crash</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/chassis-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/functional-test-area/homologation-testing</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/request-demo</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.51</priority>
        </url>
        <url>
          <loc>https://testlifecycle.pages.dev/ja/contact-us</loc>
          <lastmod>2024-04-25T04:53:52+00:00</lastmod>
          <priority>0.41</priority>
        </url>   
        </urlset>
        `.trim(),
		{
			headers: {
				'Content-Type': 'application/xml'
			}
		}
	);
};
